### ISSUE TITLE
How to obtain failure_reason from FailureSummary?

### ISSUE THREAD

**Issue by gtors** [proofit404/stories#396]
I wanna do something like this:
```python
if result.is_success:
    pass
else:
    return response.Response(
        {"code": result.???.name},   # <-- How to get access to failure_reason?
        status=status.HTTP_400_BAD_REQUEST,
    )
```

I can't figure out how to obtain `failure_reason` except iterating over all variants:

```python
next(
    failure_reason 
    for failure_reason in my_service.entrypoint.failures 
    if result.failed_because(failure_reason)
)
```

Is there a better way?

**Comment by proofit404** [comment]
Hi, thank you for the question.

The reason we can't easily expose failure reason in the summary class is composition. A story can be used in many places as part of other stories.

Every access to `my_service.entrypoint` creates an instance of the story. The creation of the new story creates a new `failures` enum.

Enums are usually used together with `is` keyword. But since we create a new enum every time the user can easily fall into this trap:

```python
result = my_service.entrypoint.run()
if result.failure_reason is my_service.entrypoint.failures.foo:
```

This will evaluate to false even if failure_reason was foo.

But this code will work as expected:
```python
entrypoint = my_service.entrypoint
result = entrypoint.run()
if result.failure_reason is entrypoint.failures.foo:
```

I can't find a way to guarantee reference transparency for such a case.

Since such bugs are very hard to find and easy to write, I decided to not expose the reason to the interface at all.

It can be introduced later if we solve the `is` keyword problem.

I hope that this makes sense. Have a good day :tada: 

Best regards,
Artem.
